### ISSUE TITLE
adapt appveyor build

### ISSUE THREAD

**Issue by clementb49** [SNVDA/snvda#2]
### Steps to reproduce:
Ask appveyor to build a branch like master.
### Actual behavior:
The build fail.
### Expected behavior:
Successful build
### roadmap
- [x] create certification autority
- [x] generate pfx certificate
- [ ] update build to use vs 2019
- [ ] update appveyor process
- [ ] remove upload update process
